using System.Globalization;

namespace SadStore.Services
{
    public class LanguageService
    {
        private readonly Dictionary<string, Dictionary<string, string>> _resources;

        public LanguageService()
        {
            _resources = new Dictionary<string, Dictionary<string, string>>
            {
                { "Checkout", new Dictionary<string, string> { { "ar", "إتمام الطلب" }, { "en", "Checkout" } } },
                { "Billing Details", new Dictionary<string, string> { { "ar", "بيانات الشحن والفاتورة" }, { "en", "Billing & Shipping Details" } } },
                { "Full Name", new Dictionary<string, string> { { "ar", "الاسم الكامل" }, { "en", "Full Name" } } },
                { "City", new Dictionary<string, string> { { "ar", "المدينة" }, { "en", "City" } } },
                { "Select City / Region", new Dictionary<string, string> { { "ar", "اختر المدينة / المنطقة" }, { "en", "Select City / Region" } } },
                { "Shipping Cost", new Dictionary<string, string> { { "ar", "تكلفة الشحن" }, { "en", "Shipping Cost" } } },
                { "Note", new Dictionary<string, string> { { "ar", "ملاحظات" }, { "en", "Note" } } },
                { "Order Notes (Optional)", new Dictionary<string, string> { { "ar", "ملاحظات حول الطلب (اختياري)" }, { "en", "Order Notes (Optional)" } } },
                { "Place Order", new Dictionary<string, string> { { "ar", "تأكيد الطلب" }, { "en", "Place Order" } } },
                { "Payment Method", new Dictionary<string, string> { { "ar", "طريقة الدفع" }, { "en", "Payment Method" } } },
                { "Pay via WhatsApp", new Dictionary<string, string> { { "ar", "الدفع وتأكيد الطلب عبر واتساب" }, { "en", "Pay & Confirm via WhatsApp" } } },
                { "Your Order", new Dictionary<string, string> { { "ar", "طلبك" }, { "en", "Your Order" } } },
                { "Free", new Dictionary<string, string> { { "ar", "مجاني" }, { "en", "Free" } } },
                { "Proceed to Checkout", new Dictionary<string, string> { { "ar", "التقدم لإتمام الطلب" }, { "en", "Proceed to Checkout" } } },
                { "Home", new Dictionary<string, string> { { "ar", "الرئيسية" }, { "en", "Home" } } },
                { "Products", new Dictionary<string, string> { { "ar", "المنتجات" }, { "en", "Products" } } },
                { "Blog", new Dictionary<string, string> { { "ar", "المدونة" }, { "en", "Blog" } } },
                { "Contact Us", new Dictionary<string, string> { { "ar", "تواصل معنا" }, { "en", "Contact Us" } } },
                { "Menu", new Dictionary<string, string> { { "ar", "القائمة" }, { "en", "Menu" } } },
                { "Search...", new Dictionary<string, string> { { "ar", "ابحث..." }, { "en", "Search..." } } },
                { "Search the store...", new Dictionary<string, string> { { "ar", "ابحث في المتجر..." }, { "en", "Search the store..." } } },
                { "Login / Register", new Dictionary<string, string> { { "ar", "دخول / تسجيل" }, { "en", "Login / Register" } } },
                { "Logout", new Dictionary<string, string> { { "ar", "تسجيل الخروج" }, { "en", "Logout" } } },
                { "My Profile", new Dictionary<string, string> { { "ar", "ملفي الشخصي" }, { "en", "My Profile" } } },
                { "Shopping Cart", new Dictionary<string, string> { { "ar", "سلة المشتريات" }, { "en", "Shopping Cart" } } },
                { "Saudi Riyal", new Dictionary<string, string> { { "ar", "ريال سعودي" }, { "en", "Saudi Riyal" } } },
                { "UAE Dirham", new Dictionary<string, string> { { "ar", "درهم إماراتي" }, { "en", "UAE Dirham" } } },
                { "SAR", new Dictionary<string, string> { { "ar", "ر.س" }, { "en", "SAR" } } },
                { "Change Main Image", new Dictionary<string, string> { { "ar", "تغيير الصورة الرئيسية" }, { "en", "Change Main Image" } } },
                { "Upload Additional Images", new Dictionary<string, string> { { "ar", "رفع صور إضافية (معرض الصور)" }, { "en", "Upload Additional Images (Gallery)" } } },
                { "Main Image", new Dictionary<string, string> { { "ar", "الصورة الرئيسية" }, { "en", "Main Image" } } },
                { "Phone", new Dictionary<string, string> { { "ar", "الهاتف" }, { "en", "Phone" } } },
                { "Saad Store", new Dictionary<string, string> { { "ar", "متجر صاد" }, { "en", "Saad Store" } } },
                { "Saad", new Dictionary<string, string> { { "ar", "صاد" }, { "en", "Saad" } } },
                { "PromoBar", new Dictionary<string, string> { { "ar", "تمتعي بخصم مميز 10% كود [صاد] - شحن مجاني للطلبات فوق 499SR" }, { "en", "Enjoy a special 10% discount with code [SAD] - Free shipping on orders over 499 SR" } } },
                { "The first destination for all women's details", new Dictionary<string, string> { { "ar", "الوجهة الأولى لجميع تفاصيل المرأة" }, { "en", "The first destination for all women's details" } } },
                { "The first destination for all women's details ✨", new Dictionary<string, string> { { "ar", "الوجهة الأولى لجميع تفاصيل المرأة✨" }, { "en", "The first destination for all women's details ✨" } } },
                { "Orders by Status", new Dictionary<string, string> { { "ar", "حالات الطلبات" }, { "en", "Orders by Status" } } },
                { "Monthly Sales", new Dictionary<string, string> { { "ar", "المبيعات الشهرية" }, { "en", "Monthly Sales" } } },
                { "Sales Overview", new Dictionary<string, string> { { "ar", "نظرة عامة على المبيعات" }, { "en", "Sales Overview" } } },
                { "Top Selling Categories", new Dictionary<string, string> { { "ar", "الأقسام الأكثر مبيعاً" }, { "en", "Top Selling Categories" } } },
                { "Jan", new Dictionary<string, string> { { "ar", "يناير" }, { "en", "Jan" } } },
                { "Feb", new Dictionary<string, string> { { "ar", "فبراير" }, { "en", "Feb" } } },
                { "Mar", new Dictionary<string, string> { { "ar", "مارس" }, { "en", "Mar" } } },
                { "Apr", new Dictionary<string, string> { { "ar", "أبريل" }, { "en", "Apr" } } },
                { "May", new Dictionary<string, string> { { "ar", "مايو" }, { "en", "May" } } },
                { "Jun", new Dictionary<string, string> { { "ar", "يونيو" }, { "en", "Jun" } } },
                { "Jul", new Dictionary<string, string> { { "ar", "يوليو" }, { "en", "Jul" } } },
                { "Aug", new Dictionary<string, string> { { "ar", "أغسطس" }, { "en", "Aug" } } },
                { "Sep", new Dictionary<string, string> { { "ar", "سبتمبر" }, { "en", "Sep" } } },
                { "Oct", new Dictionary<string, string> { { "ar", "أكتوبر" }, { "en", "Oct" } } },
                { "Nov", new Dictionary<string, string> { { "ar", "نوفمبر" }, { "en", "Nov" } } },
                { "Dec", new Dictionary<string, string> { { "ar", "ديسمبر" }, { "en", "Dec" } } },
                { "Product ID", new Dictionary<string, string> { { "ar", "رقم المنتج" }, { "en", "Product ID" } } },
                { "Category Name", new Dictionary<string, string> { { "ar", "القسم" }, { "en", "Category" } } },
                { "Created At", new Dictionary<string, string> { { "ar", "تاريخ الإضافة" }, { "en", "Created At" } } },
                { "Dashboard", new Dictionary<string, string> { { "ar", "لوحة التحكم" }, { "en", "Dashboard" } } },
                { "Important Links", new Dictionary<string, string> { { "ar", "روابط مهمة" }, { "en", "Important Links" } } },
                { "Return Policy", new Dictionary<string, string> { { "ar", "سياسة الاسترجاع" }, { "en", "Return Policy" } } },
                { "Terms & Conditions", new Dictionary<string, string> { { "ar", "الشروط والاحكام" }, { "en", "Terms & Conditions" } } },
                { "Delivery Service", new Dictionary<string, string> { { "ar", "خدمة التوصيل" }, { "en", "Delivery Service" } } },
                { "Privacy Policy", new Dictionary<string, string> { { "ar", "سياسة الخصوصية" }, { "en", "Privacy Policy" } } },
                { "Sad VIP Points", new Dictionary<string, string> { { "ar", "نقاط صاد VIP" }, { "en", "Sad VIP Points" } } },
                { "Commercial Registration", new Dictionary<string, string> { { "ar", "السجل التجاري" }, { "en", "Commercial Registration" } } },
                { "Tax Number", new Dictionary<string, string> { { "ar", "الرقم الضريبي" }, { "en", "Tax Number" } } },
                { "Download Mobile App", new Dictionary<string, string> { { "ar", "تحميل تطبيق الجوال" }, { "en", "Download Mobile App" } } },
                { "Certified on the Business Platform", new Dictionary<string, string> { { "ar", "موثق لدى منصة الأعمال" }, { "en", "Certified on the Business Platform" } } },
                { "All rights reserved © Sad 2026", new Dictionary<string, string> { { "ar", "جميع الحقوق محفوظة © صاد 2026" }, { "en", "All rights reserved © Sad 2026" } } },          
                { "Vip_Desc1", new Dictionary<string, string> { { "ar", "اجمع النقاط مع كل طلب واستبدلها كخصم على مشترياتك القادمة بكل سهولة اشتري بـ1 ريال" }, { "en", "Collect points with every order and redeem them as a discount on your next purchases easily — shop starting from 1 SAR" } } },
                { "Vip_Desc2", new Dictionary<string, string> { { "ar", "تحصل على 1 نقطة، للاستفادة من المكافآت والخصومات يجب توفر 500 نقطة أو أكثر في حسابك" }, { "en", "You earn 1 point. To benefit from rewards and discounts, you must have 500 points or more in your account" } } },
                { "Vip_Promo", new Dictionary<string, string> { { "ar", "500 نقطة = خصم 50 ريال، 1000 نقطة = خصم 100 ريال" }, { "en", "500 points = 50 SAR discount, 1000 points = 100 SAR discount" } } },
                { "Receive Points", new Dictionary<string, string> { { "ar", "إستقبال النقاط" }, { "en", "Receive Points" } } },
                { "Ways to Earn Points", new Dictionary<string, string> { { "ar", "طرق الحصول على النقاط" }, { "en", "Ways to Earn Points" } } },
                { "1 Point", new Dictionary<string, string> { { "ar", "1 نقطة" }, { "en", "1 Point" } } },
                { "Order from Store", new Dictionary<string, string> { { "ar", "الطلب من المتجر" }, { "en", "Order from Store" } } },
                { "100 Points", new Dictionary<string, string> { { "ar", "100 نقطة" }, { "en", "100 Points" } } },
                { "Rate Your Order", new Dictionary<string, string> { { "ar", "قيم طلبك" }, { "en", "Rate Your Order" } } },
                { "Rate Order", new Dictionary<string, string> { { "ar", "تقييم الطلب" }, { "en", "Rate Order" } } },
                { "25 Points", new Dictionary<string, string> { { "ar", "25 نقطة" }, { "en", "25 Points" } } },          
                { "Share Link", new Dictionary<string, string> { { "ar", "رابط المشاركة" }, { "en", "Share Link" } } },
                { "Copy Link", new Dictionary<string, string> { { "ar", "نسخ الرابط" }, { "en", "Copy Link" } } },
                { "Discounts", new Dictionary<string, string> { { "ar", "الخصومات" }, { "en", "Discounts" } } },
                { "100 SAR Discount Coupon", new Dictionary<string, string> { { "ar", "كوبون خصم 100 ريال" }, { "en", "100 SAR Discount Coupon" } } },
                { "SAR100 Discount Code", new Dictionary<string, string> { { "ar", "كود خصم SAR100" }, { "en", "SAR100 Discount Code" } } },
                { "1000 Points", new Dictionary<string, string> { { "ar", "1000 نقطة" }, { "en", "1000 Points" } } },
                { "150 SAR Discount Coupon", new Dictionary<string, string> { { "ar", "كوبون خصم 150 ريال" }, { "en", "150 SAR Discount Coupon" } } },
                { "SAR150 Discount Code", new Dictionary<string, string> { { "ar", "كود خصم SAR150" }, { "en", "SAR150 Discount Code" } } },
                { "1500 Points", new Dictionary<string, string> { { "ar", "1500 نقطة" }, { "en", "1500 Points" } } },
                { "50 SAR Discount Coupon", new Dictionary<string, string> { { "ar", "كوبون خصم 50 ريال" }, { "en", "50 SAR Discount Coupon" } } },
                { "SAR50 Discount Code", new Dictionary<string, string> { { "ar", "كود خصم SAR50" }, { "en", "SAR50 Discount Code" } } },
                { "500 Points", new Dictionary<string, string> { { "ar", "500 نقطة" }, { "en", "500 Points" } } },
                { "Item added to cart", new Dictionary<string, string> { { "ar", "تمت إضافة المنتج للسلة بنجاح" }, { "en", "Item added to cart successfully" } } },
                { "Item removed from cart", new Dictionary<string, string> { { "ar", "تم حذف المنتج من السلة" }, { "en", "Item removed from cart" } } },
                { "Cart updated", new Dictionary<string, string> { { "ar", "تم تحديث السلة" }, { "en", "Cart updated" } } },
                { "Review submitted", new Dictionary<string, string> { { "ar", "تم إرسال تقييمك وسينشر بعد المراجعة" }, { "en", "Your review has been submitted for approval" } } },
                { "Logged in successfully", new Dictionary<string, string> { { "ar", "تم تسجيل الدخول بنجاح" }, { "en", "Logged in successfully" } } },
                { "Saved successfully", new Dictionary<string, string> { { "ar", "تم الحفظ بنجاح" }, { "en", "Saved successfully" } } },
                { "Deleted successfully", new Dictionary<string, string> { { "ar", "تم الحذف بنجاح" }, { "en", "Deleted successfully" } } },
                { "Error occurred", new Dictionary<string, string> { { "ar", "حدث خطأ ما" }, { "en", "An error occurred" } } },
                { "Invalid login attempt", new Dictionary<string, string> { { "ar", "محاولة تسجيل دخول غير صحيحة" }, { "en", "Invalid login attempt" } } },
                { "Image Deleted", new Dictionary<string, string> { { "ar", "تم حذف الصورة بنجاح" }, { "en", "Image deleted successfully" } } },
                { "Abayas", new Dictionary<string, string> { { "ar", "عبايات" }, { "en", "Abayas" } } },
                { "Abaya Fabrics & Accessories", new Dictionary<string, string> { { "ar", "أقمشة عبايات وكلف" }, { "en", "Abaya Fabrics & Accessories" } } },
                { "Clothes", new Dictionary<string, string> { { "ar", "ملابس" }, { "en", "Clothes" } } },
                { "Leather Sewing & Decoration", new Dictionary<string, string> { { "ar", "حياكة وزخرفة جلود" }, { "en", "Leather Sewing & Decoration" } } },
                { "Embroidery & Lace", new Dictionary<string, string> { { "ar", "تطريز وشك" }, { "en", "Embroidery & Lace" } } },
                { "Bags & Belts", new Dictionary<string, string> { { "ar", "شنط وأحزمة" }, { "en", "Bags & Belts" } } },
                { "Raw Leather", new Dictionary<string, string> { { "ar", "جلود خام" }, { "en", "Raw Leather" } } },
                { "Supplies", new Dictionary<string, string> { { "ar", "توزيعات" }, { "en", "Supplies" } } },
                { "Casual", new Dictionary<string, string> { { "ar", "كاجوال" }, { "en", "Casual" } } },
                { "Evening", new Dictionary<string, string> { { "ar", "سهرة" }, { "en", "Evening" } } },
                { "Umrah", new Dictionary<string, string> { { "ar", "عمرة" }, { "en", "Umrah" } } },
                { "New Arrivals", new Dictionary<string, string> { { "ar", "وصل حديثًا" }, { "en", "New Arrivals" } } },
                { "Sort", new Dictionary<string, string> { { "ar", "ترتيب" }, { "en", "Sort" } } },
                { "Our Suggestions", new Dictionary<string, string> { { "ar", "مقترحاتنا" }, { "en", "Our Suggestions" } } },
                { "Newest", new Dictionary<string, string> { { "ar", "الأحدث" }, { "en", "Newest" } } },
                { "Price: High to Low", new Dictionary<string, string> { { "ar", "السعر من الاعلي للاقل" }, { "en", "Price: High to Low" } } },
                { "Price: Low to High", new Dictionary<string, string> { { "ar", "السعر من الاقل للاعلي" }, { "en", "Price: Low to High" } } },
                { "Search", new Dictionary<string, string> { { "ar", "بحث" }, { "en", "Search" } } },
                { "Price", new Dictionary<string, string> { { "ar", "السعر" }, { "en", "Price" } } },
                { "Less than 200 SAR", new Dictionary<string, string> { { "ar", "أقل من 200 ريال" }, { "en", "Less than 200 SAR" } } },
                { "200 - 400 SAR", new Dictionary<string, string> { { "ar", "200 - 400 ريال" }, { "en", "200 - 400 SAR" } } },
                { "Clear Filters", new Dictionary<string, string> { { "ar", "مسح الفلاتر" }, { "en", "Clear Filters" } } },
                { "New", new Dictionary<string, string> { { "ar", "جديد" }, { "en", "New" } } },
                { "Add to Cart", new Dictionary<string, string> { { "ar", "إضافة للسلة" }, { "en", "Add to Cart" } } },
                { "No products found matching your search.", new Dictionary<string, string> { { "ar", "لا توجد منتجات مطابقة للبحث." }, { "en", "No products found matching your search." } } },
                { "Select Size", new Dictionary<string, string> { { "ar", "اختر المقاس" }, { "en", "Select Size" } } },
                { "More than", new Dictionary<string, string> { { "ar", "أكثر من" }, { "en", "More than" } } },
                { "From", new Dictionary<string, string> { { "ar", "من" }, { "en", "From" } } },
                { "To", new Dictionary<string, string> { { "ar", "إلى" }, { "en", "To" } } },
                { "to", new Dictionary<string, string> { { "ar", "إلى" }, { "en", "to" } } },
                { "Buy Now", new Dictionary<string, string> { { "ar", "اشترِ الآن" }, { "en", "Buy Now" } } },
                { "Quick View", new Dictionary<string, string> { { "ar", "عرض سريع" }, { "en", "Quick View" } } },
                { "Wishlist", new Dictionary<string, string> { { "ar", "المفضلة" }, { "en", "Wishlist" } } },
                { "Product Number", new Dictionary<string, string> { { "ar", "رقم المنتج" }, { "en", "Product Number" } } },
                { "Quantity", new Dictionary<string, string> { { "ar", "الكمية" }, { "en", "Quantity" } } },
                { "Price includes VAT", new Dictionary<string, string> { { "ar", "السعر شامل الضريبة" }, { "en", "Price includes VAT" } } },
                { "Available", new Dictionary<string, string> { { "ar", "متوفر" }, { "en", "Available" } } },
                { "Out of Stock", new Dictionary<string, string> { { "ar", "نفذت الكمية" }, { "en", "Out of Stock" } } },
                { "Product Details", new Dictionary<string, string> { { "ar", "تفاصيل المنتج" }, { "en", "Product Details" } } },
                { "Reviews", new Dictionary<string, string> { { "ar", "التقييمات" }, { "en", "Reviews" } } },
                { "Description", new Dictionary<string, string> { { "ar", "الوصف" }, { "en", "Description" } } },
                { "Add Your Review", new Dictionary<string, string> { { "ar", "أضف تقييمك" }, { "en", "Add Your Review" } } },
                { "Rating:", new Dictionary<string, string> { { "ar", "التقييم:" }, { "en", "Rating:" } } },
                { "Rating", new Dictionary<string, string> { { "ar", "التقييم" }, { "en", "Rating" } } },
                { "Write your review here...", new Dictionary<string, string> { { "ar", "اكتب رأيك هنا..." }, { "en", "Write your review here..." } } },
                { "Submit Review", new Dictionary<string, string> { { "ar", "إرسال التقييم" }, { "en", "Submit Review" } } },
                { "You must", new Dictionary<string, string> { { "ar", "يجب عليك" }, { "en", "You must" } } },
                { "login", new Dictionary<string, string> { { "ar", "تسجيل الدخول" }, { "en", "login" } } },
                { "to write a review.", new Dictionary<string, string> { { "ar", "لكتابة تقييم." }, { "en", "to write a review." } } },
                { "Customer Reviews", new Dictionary<string, string> { { "ar", "آراء العملاء" }, { "en", "Customer Reviews" } } },
                { "No reviews yet for this product.", new Dictionary<string, string> { { "ar", "لا توجد تقييمات بعد لهذا المنتج." }, { "en", "No reviews yet for this product." } } },
                { "Related Products", new Dictionary<string, string> { { "ar", "منتجات ذات صلة" }, { "en", "Related Products" } } },
                { "No similar products.", new Dictionary<string, string> { { "ar", "لا توجد منتجات مشابهة." }, { "en", "No similar products." } } },
                { "Order Summary", new Dictionary<string, string> { { "ar", "ملخص الطلب" }, { "en", "Order Summary" } } },
                { "Subtotal (Excl. Tax)", new Dictionary<string, string> { { "ar", "مجموع المنتجات (بدون ضريبة)" }, { "en", "Subtotal (Excl. Tax)" } } },
                { "VAT (15%)", new Dictionary<string, string> { { "ar", "ضريبة القيمة المضافة (15%)" }, { "en", "VAT (15%)" } } },
                { "Total", new Dictionary<string, string> { { "ar", "الإجمالي" }, { "en", "Total" } } },
                { "Complete Order via WhatsApp", new Dictionary<string, string> { { "ar", "إتمام الطلب عبر واتساب" }, { "en", "Complete Order via WhatsApp" } } },
                { "Your cart is empty", new Dictionary<string, string> { { "ar", "سلة المشتريات فارغة" }, { "en", "Your cart is empty" } } },
                { "Browse Products", new Dictionary<string, string> { { "ar", "تصفح المنتجات" }, { "en", "Browse Products" } } },
                { "Hello, I would like to complete the following order:", new Dictionary<string, string> { { "ar", "مرحباً، أرغب بإتمام الطلب التالي:" }, { "en", "Hello, I would like to complete the following order:" } } },
                { "Please provide payment method and confirm order.", new Dictionary<string, string> { { "ar", "الرجاء تزويدي بطريقة الدفع وتأكيد الطلب." }, { "en", "Please provide payment method and confirm order." } } },
                { "Login", new Dictionary<string, string> { { "ar", "تسجيل الدخول" }, { "en", "Login" } } },
                { "Create Account", new Dictionary<string, string> { { "ar", "إنشاء حساب" }, { "en", "Create Account" } } },
                { "Sign In", new Dictionary<string, string> { { "ar", "تسجيل الدخول" }, { "en", "Sign In" } } },
                { "Sign Up", new Dictionary<string, string> { { "ar", "إنشاء حساب" }, { "en", "Sign Up" } } },
                { "Password", new Dictionary<string, string> { { "ar", "كلمة المرور" }, { "en", "Password" } } },
                { "Name", new Dictionary<string, string> { { "ar", "الاسم" }, { "en", "Name" } } },
                { "Forgot your password?", new Dictionary<string, string> { { "ar", "هل نسيت كلمة المرور؟" }, { "en", "Forgot your password?" } } },
                { "Welcome Back!", new Dictionary<string, string> { { "ar", "مرحباً بعودتك!" }, { "en", "Welcome Back!" } } },
                { "To keep connected with us please login with your personal info", new Dictionary<string, string> { { "ar", "للبقاء على تواصل معنا، يرجى تسجيل الدخول باستخدام بياناتك" }, { "en", "To keep connected with us please login with your personal info" } } },
                { "Hello, Friend!", new Dictionary<string, string> { { "ar", "أهلاً بك!" }, { "en", "Hello, Friend!" } } },
                { "Enter your personal details and start journey with us", new Dictionary<string, string> { { "ar", "أدخل بياناتك وابدأ إنشاء حسابك معنا" }, { "en", "Enter your personal details and start journey with us" } } },
                { "or use your email for registration", new Dictionary<string, string> { { "ar", "أو استخدم بريدك الإلكتروني للتسجيل" }, { "en", "or use your email for registration" } } },
                { "or use your account", new Dictionary<string, string> { { "ar", "أو سجّل الدخول باستخدام حسابك" }, { "en", "or use your account" } } },
                { "Notifications", new Dictionary<string, string> { { "ar", "الإشعارات" }, { "en", "Notifications" } } },
                { "No notifications", new Dictionary<string, string> { { "ar", "لا توجد إشعارات" }, { "en", "No notifications" } } },
                { "Orders", new Dictionary<string, string> { { "ar", "الطلبات" }, { "en", "Orders" } } },
                { "No orders", new Dictionary<string, string> { { "ar", "لا توجد طلبات" }, { "en", "No orders" } } },
                { "Pending Payments", new Dictionary<string, string> { { "ar", "طلبات بانتظار الدفع" }, { "en", "Pending Payments" } } },
                { "No payment requests", new Dictionary<string, string> { { "ar", "لا توجد طلبات دفع" }, { "en", "No payment requests" } } },
                { "No items", new Dictionary<string, string> { { "ar", "لا توجد عناصر" }, { "en", "No items" } } },
                { "My Wallet", new Dictionary<string, string> { { "ar", "محفظتي" }, { "en", "My Wallet" } } },
                { "Loyalty Points", new Dictionary<string, string> { { "ar", "نقاط الولاء" }, { "en", "Loyalty Points" } } },
                { "My Account", new Dictionary<string, string> { { "ar", "حسابي" }, { "en", "My Account" } } },
                { "Phone Number", new Dictionary<string, string> { { "ar", "رقم الهاتف" }, { "en", "Phone Number" } } },
                { "Save Changes2", new Dictionary<string, string> { { "ar", "حفظ التغييرات" }, { "en", "Save Changes" } } },
                { "Are you sure you want to logout?", new Dictionary<string, string> { { "ar", "هل أنت متأكد من تسجيل الخروج؟" }, { "en", "Are you sure you want to logout?" } } },
                { "Return Order", new Dictionary<string, string> { { "ar", "طلب إرجاع" }, { "en", "Return Order" } } },
                { "Return window expired", new Dictionary<string, string> { { "ar", "انتهت فترة الإرجاع" }, { "en", "Return window expired" } } },
                { "Order History", new Dictionary<string, string> { { "ar", "سجل الطلبات" }, { "en", "Order History" } } },
                { "Order ID", new Dictionary<string, string> { { "ar", "رقم الطلب" }, { "en", "Order ID" } } },
                { "Date", new Dictionary<string, string> { { "ar", "التاريخ" }, { "en", "Date" } } },
                { "Status", new Dictionary<string, string> { { "ar", "الحالة" }, { "en", "Status" } } },
                { "Details", new Dictionary<string, string> { { "ar", "التفاصيل" }, { "en", "Details" } } },
                { "No previous orders found", new Dictionary<string, string> { { "ar", "لا توجد طلبات سابقة" }, { "en", "No previous orders found" } } },
                { "جديد", new Dictionary<string, string> { { "ar", "جديد" }, { "en", "New" } } },
                { "قيد التنفيذ", new Dictionary<string, string> { { "ar", "قيد التنفيذ" }, { "en", "In Progress" } } },
                { "مكتمل", new Dictionary<string, string> { { "ar", "مكتمل" }, { "en", "Completed" } } },
                { "ملغي", new Dictionary<string, string> { { "ar", "ملغي" }, { "en", "Cancelled" } } },
                { "About Us", new Dictionary<string, string> { { "ar", "من نحن" }, { "en", "About Us" } } },
                { "About Saad", new Dictionary<string, string> { { "ar", "عن صاد" }, { "en", "About Saad" } } },
                { "Happy Customer", new Dictionary<string, string> { { "ar", "عميل سعيد" }, { "en", "Happy Customer" } } },
                { "Various Products", new Dictionary<string, string> { { "ar", "منتج متنوع" }, { "en", "Various Products" } } },
                { "Technical Support", new Dictionary<string, string> { { "ar", "دعم فني" }, { "en", "Technical Support" } } },
                { "We are happy to connect with you via the following channels", new Dictionary<string, string> { { "ar", "يسعدنا تواصلكم معنا عبر القنوات التالية" }, { "en", "We are happy to connect with you via the following channels" } } },
                { "Customer Service WhatsApp", new Dictionary<string, string> { { "ar", "خدمة العملاء واتساب" }, { "en", "Customer Service WhatsApp" } } },
                { "Unified Phone", new Dictionary<string, string> { { "ar", "الهاتف الموحد" }, { "en", "Unified Phone" } } },
                { "Privacy Policy Content", new Dictionary<string, string> { { "ar", "نحن في صاد نحترم خصوصيتك وحقك باختيار كيفية استخدام المعلومات الخاصة بك. إن من أهم أولوياتنا الحرص على حماية المعلومات التي بحوزتنا." }, { "en", "At Saad, we respect your privacy and your right to choose how your information is used. One of our top priorities is protecting the information we hold." } } },
                { "Privacy Policy Detail", new Dictionary<string, string> { { "ar", "نحن لا نشارك معلومات العملاء (بما في ذلك عناوين البريد الإلكتروني) مع أي طرف ما لم يكن ذلك ضرورياً لغاية توفير المنتجات والخدمات التي نقدمها. كما أننا لن نكشف عن أي معلومات إلا عندما تعطينا الحق للقيام بذلك." }, { "en", "We do not share customer information (including email addresses) with any third party unless necessary to provide the products and services we offer. We will only disclose information when we have the right to do so." } } },
                { "Payment Security", new Dictionary<string, string> { { "ar", "أمان الدفع: نحن لا نحتفظ بأي تفاصيل لبطاقة الائتمان الخاصة بك." }, { "en", "Payment Security: We do not store any details of your credit card." } } },
                { "Privacy Contact", new Dictionary<string, string> { { "ar", "إذا كان لديك أي أسئلة أو مخاوف بشأن وصول أو استخدام صاد لمعلوماتك الشخصية، يرجى مراسلتنا على البريد الإلكتروني أو رقم الهاتف 920010063." }, { "en", "If you have any questions or concerns about Saad's access to or use of your personal information, please contact us via email or at phone number 920010063." } } },
                { "Delivery Content", new Dictionary<string, string> { { "ar", "في حال كان عنوان العميل خارج نطاق التوصيل الخاص بشركة الشحن، سيتم توجيه الشحنة إلى أقرب فرع تابع للشركة في منطقة العميل، حيث يمكن للعميل استلام الشحنة مباشرة من المكتب المحدد." }, { "en", "If the customer's address is outside the shipping company's delivery area, the shipment will be directed to the nearest branch of the company in the customer's area, where the customer can collect the shipment directly from the designated office." } } },
                { "Local Delivery", new Dictionary<string, string> { { "ar", "التوصيل داخل المملكة" }, { "en", "Local Delivery" } } },
                { "International Delivery", new Dictionary<string, string> { { "ar", "التوصيل الدولي" }, { "en", "International Delivery" } } },
                { "Delivery Time Local", new Dictionary<string, string> { { "ar", "مدة التوصيل: من ٤ الى ٧ أيام عمل" }, { "en", "Delivery Time: 4 to 7 working days" } } },
                { "Delivery Companies", new Dictionary<string, string> { { "ar", "شركات الشحن: أرامكس - سمسا" }, { "en", "Shipping Companies: Aramex - SMSA" } } },
                { "Delivery Time Int", new Dictionary<string, string> { { "ar", "يستغرق من ١٠ الى ١٥ يوم عمل" }, { "en", "Takes 10 to 15 working days" } } },
                { "Return Method Content", new Dictionary<string, string> { { "ar", "تواصل معنا عبر الواتساب لبدء الاسترجاع" }, { "en", "Contact us via WhatsApp to start the return" } } },
                { "Return Response", new Dictionary<string, string> { { "ar", "سيقوم فريق خدمة العملاء بالرد عليكم وتزويدكم ببوليصة الشحن خلال 48 ساعة." }, { "en", "Our customer service team will respond to you and provide the shipping policy within 48 hours." } } },
                { "Invite Your Friends", new Dictionary<string, string> { { "ar", "شارك أصدقائك" }, { "en", "Invite Your Friends" } } },
                { "Shop Now", new Dictionary<string, string> { { "ar", "تسوق الآن" }, { "en", "Shop Now" } } },
                { "Points", new Dictionary<string, string> { { "ar", "نقطة" }, { "en", "Points" } } },              
                { "Collect points...", new Dictionary<string, string> { { "ar", "اجمع النقاط مع كل طلب واستبدلها كخصم على مشترياتك القادمة بكل سهولة اشتري بـ1 ريال" }, { "en", "Collect points with every order and redeem them as a discount on your next purchases easily — shop starting from 1 SAR" } } },
                { "You earn 1 point...", new Dictionary<string, string> { { "ar", "تحصل على 1 نقطة، للاستفادة من المكافآت والخصومات يجب توفر 500 نقطة أو أكثر في حسابك" }, { "en", "You earn 1 point. To benefit from rewards and discounts, you must have 500 points or more in your account" } } },
                { "500 points...", new Dictionary<string, string> { { "ar", "500 نقطة = خصم 50 ريال، 1000 نقطة = خصم 100 ريال" }, { "en", "500 points = 50 SAR discount, 1000 points = 100 SAR discount" } } },
                { "Terms and conditions for the winter gift offer:", new Dictionary<string, string> { { "ar", "الشروط والأحكام عرض هدية شتوية :" }, { "en", "Terms and conditions for the winter gift offer:" } } },
                { "Gifts are given...", new Dictionary<string, string> { { "ar", "الهدايا تُمنح لجميع الطلبات حتى نفاد الكمية." }, { "en", "Gifts are given to all orders until stocks run out." } } },
                { "In case of order return...", new Dictionary<string, string> { { "ar", "في حال استرجاع الطلب، يجب إعادة الهدية المرفقة لإتمام استرداد المبلغ." }, { "en", "In case of order return, the included gift must be returned to complete the refund." } } },
                { "Orders up to 199...", new Dictionary<string, string> { { "ar", "الطلبات حتى 199 ريال : هدية واحدة بلوزة شتوية." }, { "en", "Orders up to 199 riyals: One free winter blouse." } } },
                { "Orders over 599...", new Dictionary<string, string> { { "ar", "الطلبات أكثر من 599 ريال : هديتان شتوية." }, { "en", "Orders over 599 riyals: Two winter gifts." } } },
                { "Terms and conditions for the accessory gift offer:", new Dictionary<string, string> { { "ar", "الشروط والأحكام عرض هدية الاكسسوار :" }, { "en", "Terms and conditions for the accessory gift offer:" } } },
                { "Orders up to 599 riyals: One free...", new Dictionary<string, string> { { "ar", "الطلبات حتى 599 ريال : هدية قطعة واحدة مجانية من صاد ." }, { "en", "Orders up to 599 riyals: One free piece of saad as a gift." } } },
                { "Orders of 600...", new Dictionary<string, string> { { "ar", "الطلبات من 600 ريال و أكثر : هدية قطعة واحدة مجانية من صاد + اكسسوار هدية ." }, { "en", "Orders of 600 riyals and more: One free piece of saad gift + a gift accessory." } } },
                { "At Saad, we strive...", new Dictionary<string, string> {
                { "ar", "نحن في \"صاد\" نسعى لتقديم أرقى الأزياء النسائية التي تجمع بين الأصالة والعصرية. تأسس متجرنا ليكون ملاذك الأول للبحث عن العبايات الفاخرة، الأقمشة الراقية، والملابس التي تعكس شخصيتك الفريدة." },
                { "en", "At Saad, we strive to provide the finest women's fashion that combines authenticity and modernity. Our store was established to be your first destination for luxury abayas, high-end fabrics, and clothes that reflect your unique personality." } } },
                { "We pay attention...", new Dictionary<string, string> {
                { "ar", "نهتم بأدق التفاصيل، من اختيار الخامات إلى دقة التصميم، لنضمن لكِ إطلالة مميزة في كل المناسبات. سواء كنتِ تبحثين عن عباية يومية عملية أو فستان سهرة يخطف الأنظار، ستجدين في صاد ما يرضي ذوقك." },
                { "en", "We pay attention to the smallest details, from selecting materials to design precision, to ensure you a distinctive look on all occasions. Whether you are looking for a practical daily abaya or an eye-catching evening dress, you will find at Saad what satisfies your taste." } } },
                { "View Site", new Dictionary<string, string> { { "ar", "عرض الموقع" }, { "en", "View Site" } } },
                { "Saad Panel", new Dictionary<string, string> { { "ar", "لوحة صاد" }, { "en", "Saad Panel" } } },
                { "Total Orders", new Dictionary<string, string> { { "ar", "إجمالي الطلبات" }, { "en", "Total Orders" } } },
                { "Total Revenue", new Dictionary<string, string> { { "ar", "إجمالي المبيعات" }, { "en", "Total Revenue" } } },
                { "Total Products", new Dictionary<string, string> { { "ar", "عدد المنتجات" }, { "en", "Total Products" } } },
                { "New Orders", new Dictionary<string, string> { { "ar", "طلبات جديدة" }, { "en", "New Orders" } } },
                { "Recent Orders", new Dictionary<string, string> { { "ar", "آخر الطلبات المستلمة" }, { "en", "Recent Orders" } } },
                { "View All", new Dictionary<string, string> { { "ar", "عرض الكل" }, { "en", "View All" } } },
                { "Order Number", new Dictionary<string, string> { { "ar", "رقم الطلب" }, { "en", "Order Number" } } },
                { "Customer", new Dictionary<string, string> { { "ar", "العميل" }, { "en", "Customer" } } },
                { "Amount", new Dictionary<string, string> { { "ar", "المبلغ" }, { "en", "Amount" } } },
                { "Actions", new Dictionary<string, string> { { "ar", "الإجراءات" }, { "en", "Actions" } } },
                { "Product List", new Dictionary<string, string> { { "ar", "قائمة المنتجات" }, { "en", "Product List" } } },
                { "Add New Product", new Dictionary<string, string> { { "ar", "إضافة منتج جديد" }, { "en", "Add New Product" } } },
                { "Edit", new Dictionary<string, string> { { "ar", "تعديل" }, { "en", "Edit" } } },
                { "Delete", new Dictionary<string, string> { { "ar", "حذف" }, { "en", "Delete" } } },
                { "Confirm Delete", new Dictionary<string, string> { { "ar", "تأكيد الحذف" }, { "en", "Confirm Delete" } } },
                { "Are you sure you want to delete", new Dictionary<string, string> { { "ar", "هل أنت متأكد من حذف" }, { "en", "Are you sure you want to delete" } } },
                { "Cancel", new Dictionary<string, string> { { "ar", "إلغاء" }, { "en", "Cancel" } } },
                { "Save Product", new Dictionary<string, string> { { "ar", "حفظ المنتج" }, { "en", "Save Product" } } },
                { "Product Name (Ar)", new Dictionary<string, string> { { "ar", "اسم المنتج (عربي)" }, { "en", "Product Name (Ar)" } } },
                { "Product Name (En)", new Dictionary<string, string> { { "ar", "اسم المنتج (إنجليزي)" }, { "en", "Product Name (En)" } } },
                { "Description (Ar)", new Dictionary<string, string> { { "ar", "الوصف (عربي)" }, { "en", "Description (Ar)" } } },
                { "Description (En)", new Dictionary<string, string> { { "ar", "الوصف (إنجليزي)" }, { "en", "Description (En)" } } },
                { "Product Image", new Dictionary<string, string> { { "ar", "صورة المنتج" }, { "en", "Product Image" } } },
                { "Product Images", new Dictionary<string, string> { { "ar", "صور المنتج" }, { "en", "Product Images" } } },
                { "Additional Images", new Dictionary<string, string> { { "ar", "صور إضافية" }, { "en", "Additional Images" } } },
                { "Upload New Images", new Dictionary<string, string> { { "ar", "رفع صور جديدة" }, { "en", "Upload New Images" } } },
                { "Delete Image", new Dictionary<string, string> { { "ar", "حذف الصورة" }, { "en", "Delete Image" } } },
                { "Display on Home Page", new Dictionary<string, string> { { "ar", "عرض في الصفحة الرئيسية (منتج مميز)" }, { "en", "Display on Home Page (Featured)" } } },
                { "Categories", new Dictionary<string, string> { { "ar", "الأقسام" }, { "en", "Categories" } } },
                { "Category List", new Dictionary<string, string> { { "ar", "قائمة الأقسام" }, { "en", "Category List" } } },
                { "Add New Category", new Dictionary<string, string> { { "ar", "إضافة قسم جديد" }, { "en", "Add New Category" } } },
                { "Category Name (Ar)", new Dictionary<string, string> { { "ar", "اسم القسم (عربي)" }, { "en", "Category Name (Ar)" } } },
                { "Category Name (En)", new Dictionary<string, string> { { "ar", "اسم القسم (إنجليزي)" }, { "en", "Category Name (En)" } } },
                { "Product Count", new Dictionary<string, string> { { "ar", "عدد المنتجات" }, { "en", "Product Count" } } },
                { "Save Category", new Dictionary<string, string> { { "ar", "حفظ القسم" }, { "en", "Save Category" } } },
                { "Category", new Dictionary<string, string> { { "ar", "القسم" }, { "en", "Category" } } },
                { "Image", new Dictionary<string, string> { { "ar", "الصورة" }, { "en", "Image" } } },
                { "Product Name", new Dictionary<string, string> { { "ar", "اسم المنتج" }, { "en", "Product Name" } } },
                { "Stock", new Dictionary<string, string> { { "ar", "المخزون" }, { "en", "Stock" } } },
                { "Featured", new Dictionary<string, string> { { "ar", "مميز" }, { "en", "Featured" } } },
                { "Back to List", new Dictionary<string, string> { { "ar", "عودة للقائمة" }, { "en", "Back to List" } } },
                { "Users", new Dictionary<string, string> { { "ar", "المستخدمين" }, { "en", "Users" } } },
                { "Shipping", new Dictionary<string, string> { { "ar", "الشحن" }, { "en", "Shipping" } } },
                { "Sold Out", new Dictionary<string, string> { { "ar", "نفذت الكمية" }, { "en", "Sold Out" } } },
                { "Uncategorized", new Dictionary<string, string> { { "ar", "غير مصنف" }, { "en", "Uncategorized" } } },
                { "Edit Category", new Dictionary<string, string> { { "ar", "تعديل القسم" }, { "en", "Edit Category" } } },
                { "Edit Product", new Dictionary<string, string> { { "ar", "تعديل المنتج" }, { "en", "Edit Product" } } },
                { "Current Image", new Dictionary<string, string> { { "ar", "الصورة الحالية" }, { "en", "Current Image" } } },
                { "Save Changes", new Dictionary<string, string> { { "ar", "حفظ التغييرات" }, { "en", "Save Changes" } } },
                { "Update Status", new Dictionary<string, string> { { "ar", "تحديث الحالة" }, { "en", "Update Status" } } },
                { "Current Status", new Dictionary<string, string> { { "ar", "الحالة الحالية" }, { "en", "Current Status" } } },
                { "Print Invoice", new Dictionary<string, string> { { "ar", "طباعة الفاتورة" }, { "en", "Print Invoice" } } },
                { "Order Details", new Dictionary<string, string> { { "ar", "تفاصيل الطلب" }, { "en", "Order Details" } } },
                { "Customer Info", new Dictionary<string, string> { { "ar", "معلومات العميل" }, { "en", "Customer Info" } } },
                { "Unit Price", new Dictionary<string, string> { { "ar", "سعر الوحدة" }, { "en", "Unit Price" } } },
                { "Subtotal", new Dictionary<string, string> { { "ar", "المجموع الفرعي" }, { "en", "Subtotal" } } },
                { "Address", new Dictionary<string, string> { { "ar", "العنوان" }, { "en", "Address" } } },
                { "Order List", new Dictionary<string, string> { { "ar", "سجل الطلبات" }, { "en", "Order List" } } },
                { "Shipping Locations", new Dictionary<string, string> { { "ar", "مناطق الشحن" }, { "en", "Shipping Locations" } } },
                { "Add New Location", new Dictionary<string, string> { { "ar", "إضافة منطقة جديدة" }, { "en", "Add New Location" } } },
                { "City / Region", new Dictionary<string, string> { { "ar", "المدينة / المنطقة" }, { "en", "City / Region" } } },
                { "Cost", new Dictionary<string, string> { { "ar", "التكلفة" }, { "en", "Cost" } } },
                { "Save Location", new Dictionary<string, string> { { "ar", "حفظ المنطقة" }, { "en", "Save Location" } } },
                { "Edit Location", new Dictionary<string, string> { { "ar", "تعديل المنطقة" }, { "en", "Edit Location" } } },
                { "Blog Posts", new Dictionary<string, string> { { "ar", "المقالات المنشورة" }, { "en", "Blog Posts" } } },
                { "Add New Post", new Dictionary<string, string> { { "ar", "إضافة مقال جديد" }, { "en", "Add New Post" } } },
                { "Title", new Dictionary<string, string> { { "ar", "العنوان" }, { "en", "Title" } } },
                { "Published Date", new Dictionary<string, string> { { "ar", "تاريخ النشر" }, { "en", "Published Date" } } },
                { "Content", new Dictionary<string, string> { { "ar", "المحتوى" }, { "en", "Content" } } },
                { "Publish Post", new Dictionary<string, string> { { "ar", "نشر المقال" }, { "en", "Publish Post" } } },
                { "Edit Post", new Dictionary<string, string> { { "ar", "تعديل المقال" }, { "en", "Edit Post" } } },
                { "Published", new Dictionary<string, string> { { "ar", "منشور" }, { "en", "Published" } } },
                { "Pending", new Dictionary<string, string> { { "ar", "قيد المراجعة" }, { "en", "Pending" } } },
                { "Back to Blog", new Dictionary<string, string> { { "ar", "العودة إلى المدونة" }, { "en", "Back to Blog" } } },
                { "No posts found", new Dictionary<string, string> { { "ar", "لا توجد مقالات منشورة حالياً" }, { "en", "No blog posts found at the moment" } } },
                { "Export to Excel", new Dictionary<string, string> { { "ar", "تصدير إلى إكسل" }, { "en", "Export to Excel" } } },
                { "Filter", new Dictionary<string, string> { { "ar", "تصفية" }, { "en", "Filter" } } },
                { "Next", new Dictionary<string, string> { { "ar", "التالي" }, { "en", "Next" } } },
                { "Previous", new Dictionary<string, string> { { "ar", "السابق" }, { "en", "Previous" } } },
                { "Page", new Dictionary<string, string> { { "ar", "صفحة" }, { "en", "Page" } } },
                { "Of", new Dictionary<string, string> { { "ar", "من" }, { "en", "of" } } },
                { "All Categories", new Dictionary<string, string> { { "ar", "كل الأقسام" }, { "en", "All Categories" } } },
                { "From Date", new Dictionary<string, string> { { "ar", "من تاريخ" }, { "en", "From Date" } } },
                { "To Date", new Dictionary<string, string> { { "ar", "إلى تاريخ" }, { "en", "To Date" } } },
                { "Product Specifications", new Dictionary<string, string> { { "ar", "مواصفات المنتج" }, { "en", "Product Specifications" } } },
                { "Design Type", new Dictionary<string, string> { { "ar", "نوع التصميم" }, { "en", "Design Type" } } },
                { "Cut Type", new Dictionary<string, string> { { "ar", "نوع القصة" }, { "en", "Cut Type" } } },
                { "Occasion", new Dictionary<string, string> { { "ar", "المناسبة" }, { "en", "Occasion" } } },
                { "Fit Type", new Dictionary<string, string> { { "ar", "الحجم/الوسع" }, { "en", "Fit Type" } } },
                { "Lining", new Dictionary<string, string> { { "ar", "البطانة" }, { "en", "Lining" } } },
                { "Sleeves", new Dictionary<string, string> { { "ar", "الأكمام" }, { "en", "Sleeves" } } },
                { "Stretch", new Dictionary<string, string> { { "ar", "التمدد" }, { "en", "Stretch" } } },
                { "Material", new Dictionary<string, string> { { "ar", "الخامة" }, { "en", "Material" } } },
                { "Care Instructions", new Dictionary<string, string> { { "ar", "إرشادات العناية" }, { "en", "Care Instructions" } } },
                { "Model Number", new Dictionary<string, string> { { "ar", "رقم الموديل" }, { "en", "Model Number" } } },
                { "Old Price", new Dictionary<string, string> { { "ar", "السعر القديم (قبل الخصم)" }, { "en", "Old Price (Before Discount)" } } },
                { "Current Price", new Dictionary<string, string> { { "ar", "السعر الحالي (بعد الخصم)" }, { "en", "Current Price (After Discount)" } } },
                { "Available Sizes", new Dictionary<string, string> { { "ar", "المقاسات المتاحة" }, { "en", "Available Sizes" } } },
                { "Sizes Note", new Dictionary<string, string> { { "ar", "افصل بين المقاسات بفاصلة (مثال: S,M,L)" }, { "en", "Separate sizes with a comma (e.g., S,M,L)" } } },
                { "Delivery Content2", new Dictionary<string, string> { { "ar", "في حال كان عنوان العميل خارج نطاق التوصيل الخاص بشركة الشحن، سيتم توجيه الشحنة إلى أقرب فرع تابع للشركة في منطقة العميل، حيث يمكن للعميل استلام الشحنة مباشرة من المكتب المحدد." }, { "en", "If the customer's address is outside the shipping company's delivery area, the shipment will be directed to the nearest branch of the company in the customer's area, where the customer can collect the shipment directly from the designated office." } } },
                { "Local Delivery2", new Dictionary<string, string> { { "ar", "مدة التوصيل داخل مدن المملكة" }, { "en", "Delivery duration within Kingdom cities" } } },
                { "International Delivery2", new Dictionary<string, string> { { "ar", "مدة التوصيل الدولي" }, { "en", "International Delivery Duration" } } },
                { "Delivery Time Local2", new Dictionary<string, string> { { "ar", "من ٤ الى ٧ أيام عمل" }, { "en", "From 4 to 7 working days" } } },
                { "Delivery Companies2", new Dictionary<string, string> { { "ar", "شركات الشحن: أرامكس - سمسا" }, { "en", "Shipping Companies: Aramex - SMSA" } } },
                { "Delivery Time Int2", new Dictionary<string, string> { { "ar", "يستغرق من ١٠ الى ١٥ يوم عمل" }, { "en", "Takes 10 to 15 working days" } } },
                { "Int Delivery Company", new Dictionary<string, string> { { "ar", "شركة الشحن : أرامكس" }, { "en", "Shipping Company: Aramex" } } },
                { "Gift Policy", new Dictionary<string, string> { { "ar", "سياسة الهدية" }, { "en", "Gift Policy" } } },
                { "Terms_WinterOffer", new Dictionary<string, string> { { "ar", "الشروط والأحكام عرض هدية شتوية :" }, { "en", "Terms and conditions for the winter gift offer:" } } },
                { "Terms_AccessoryOffer", new Dictionary<string, string> { { "ar", "الشروط والأحكام عرض هدية الاكسسوار :" }, { "en", "Terms and conditions for the accessory gift offer:" } } },
                { "Gift_StockCondition", new Dictionary<string, string> { { "ar", "الهدايا تُمنح لجميع الطلبات حتى نفاد الكمية." }, { "en", "Gifts are granted to all orders while stocks last." } } },
                { "Gift_ReturnCondition", new Dictionary<string, string> { { "ar", "في حال استرجاع الطلب، يجب إعادة الهدية المرفقة لإتمام استرداد المبلغ." }, { "en", "In case of order return, the included gift must be returned to complete the refund." } } },
                { "Gift_Winter_199", new Dictionary<string, string> { { "ar", "الطلبات حتى 199 ريال : هدية واحدة بلوزة شتوية." }, { "en", "Orders up to 199 SAR: One free winter blouse." } } },
                { "Gift_Winter_599", new Dictionary<string, string> { { "ar", "الطلبات أكثر من 599 ريال : هديتان شتوية." }, { "en", "Orders over 599 SAR: Two winter gifts." } } },
                { "Gift_Accessory_599", new Dictionary<string, string> { { "ar", "الطلبات حتى 599 ريال : هدية قطعة واحدة مجانية من صاد ." }, { "en", "Orders up to 599 SAR: One free piece from Saad." } } },
                { "Gift_Accessory_600", new Dictionary<string, string> { { "ar", "الطلبات من 600 ريال و أكثر : هدية قطعة واحدة مجانية من صاد + اكسسوار هدية ." }, { "en", "Orders of 600 SAR and more: One free piece from Saad + Gift Accessory." } } },
                { "Return Method", new Dictionary<string, string> { { "ar", "طريقة الاسترجاع" }, { "en", "Return Method" } } },
                { "ReturnMethod_Action", new Dictionary<string, string> { { "ar", "تواصل معنا عبر الواتساب لبدء الاسترجاع" }, { "en", "Contact us via WhatsApp to start return" } } },
                { "ReturnMethod_Note", new Dictionary<string, string> { { "ar", "سيقوم فريق خدمة العملاء بالرد عليكم وتزويدكم ببوليصة الشحن خلال 48 ساعة." }, { "en", "Our customer service team will respond and provide the shipping policy within 48 hours." } } },
                { "Get in Touch", new Dictionary<string, string> { { "ar", "تواصل معنا" }, { "en", "Get in Touch" } } },
                { "We are here to help", new Dictionary<string, string> { { "ar", "نحن هنا للمساعدة" }, { "en", "We are here to help" } } },
                { "Email", new Dictionary<string, string> { { "ar", "البريد الإلكتروني" }, { "en", "Email" } } },
                { "SaadProfile", new Dictionary<string, string> { { "ar", "صاد" }, { "en", "Saad" } } },
                { "RP_StartLink", new Dictionary<string, string> { { "ar", "انقر على هذا الرابط لبدء عملية الإرجاع" }, { "en", "Click this link to start the return process" } } },
                { "RP_Intro", new Dictionary<string, string> { { "ar", "لتجربة تسوق أفضل، أضفنا خيارات جديدة:" }, { "en", "For a better shopping experience, we added new options:" } } },
                { "RP_Fee", new Dictionary<string, string> { { "ar", "عند استرجاع منتج أو الطلب كاملًا، يتم خصم رسوم الاسترجاع وقدرها 29 ريال سعودي من المبلغ المسترد." }, { "en", "When returning a product or the entire order, a return fee of 29 SAR will be deducted from the refund amount." } } },
                { "RP_Window", new Dictionary<string, string> { { "ar", "يمكنك إرجاع المنتج خلال 7 أيام من تاريخ الاستلام." }, { "en", "You can return the product within 7 days of receipt." } } },
                { "RP_NoStoreReturn", new Dictionary<string, string> { { "ar", "لا يوجد استرجاع أو استبدال لطلبات الموقع الإلكتروني من الفروع" }, { "en", "No return or exchange for online orders at branches." } } },
                { "RP_NoExchange", new Dictionary<string, string> { { "ar", "لا يُسمح باستبدال المنتجات المشتراة من المتجر الإلكتروني." }, { "en", "Exchange of products purchased from the online store is not allowed." } } },
                { "RP_OriginalCondition", new Dictionary<string, string> { { "ar", "يجب أن يكون المنتج في حالته الأصلية دون تلف." }, { "en", "The product must be in its original condition without damage." } } },
                { "RP_Exception", new Dictionary<string, string> { { "ar", "تنطبق سياسة الإرجاع على جميع المنتجات باستثناء الملحقات." }, { "en", "The return policy applies to all products except accessories." } } },
                { "RP_PromoTitle", new Dictionary<string, string> { { "ar", "شروط وأحكام إرجاع العروض الترويجية" }, { "en", "Promotional Offer Return Terms & Conditions" } } },
                { "RP_PromoPoint", new Dictionary<string, string> { { "ar", "يجب إرجاع جميع المنتجات المشمولة في العرض الترويجي بالكامل." }, { "en", "All products included in the promotional offer must be returned in full." } } },
                { "RP_StepsTitle", new Dictionary<string, string> { { "ar", "خطوات الإرجاع" }, { "en", "Return Steps" } } },
                { "RP_Step1", new Dictionary<string, string> { { "ar", "ادخل إلى لوحة طلباتي" }, { "en", "Go to My Orders panel" } } },
                { "RP_Step2", new Dictionary<string, string> { { "ar", "أنشئ نموذج الإرجاع" }, { "en", "Create Return Form" } } },
                { "RP_Step3", new Dictionary<string, string> { { "ar", "سيتم إرسال السياسة خلال 48 ساعة إلى بريدك الإلكتروني" }, { "en", "The policy will be sent to your email within 48 hours" } } },
                { "RP_NotesTitle", new Dictionary<string, string> { { "ar", "ملاحظات" }, { "en", "Notes" } } },
                { "RP_Note1", new Dictionary<string, string> { { "ar", "لا يمكن إلغاء الطلب بعد التأكيد." }, { "en", "The order cannot be cancelled after confirmation." } } },
                { "RP_Note2", new Dictionary<string, string> { { "ar", "يتم استرداد المبلغ خلال 14 يوم عمل." }, { "en", "The amount will be refunded within 14 working days." } } },
                { "Working Hours", new Dictionary<string, string> { { "ar", "ساعات العمل" }, { "en", "Working Hours" } } },
                { "Sunday to Thursday", new Dictionary<string, string> { { "ar", "من الأحد إلى الخميس" }, { "en", "Sunday to Thursday" } } },
                { "9:00 AM - 9:00 PM", new Dictionary<string, string> { { "ar", "9:00 صباحاً - 9:00 مساءً" }, { "en", "9:00 AM - 9:00 PM" } } },
                { "Terms_Intro_Title", new Dictionary<string, string> { { "ar", "الشروط والأحكام" }, { "en", "Terms & Conditions" } } },
                { "Terms_IP_Title", new Dictionary<string, string> { { "ar", "الملكية الفكرية والترخيص" }, { "en", "Intellectual Property & License" } } },
                { "Terms_IP_Body", new Dictionary<string, string> {
                { "ar", "يشكل كل المحتوى المتوفر على هذا الموقع (بما في ذلك النصوص، التصميم، الرسومات، الشعارات، الأيقونات، الصور، المقاطع الصوتية، والبرامج) ملكية حصرية لـ (صاد) والمرخصين لها. تمنحك (صاد) ترخيصاً محدوداً لاستخدام هذا الموقع استخداماً شخصياً. تحتفظ (صاد) بالملكية الكاملة لهذا المحتوى." },
                { "en", "All content available on this site (including text, design, graphics, logos, icons, images, audio clips, and software) is the exclusive property of (Saad) and its licensors. Saad grants you a limited license for personal use of this site. Saad retains full ownership of this content." }} },
                { "Terms_Flash_Title", new Dictionary<string, string> { { "ar", "خصم فلاش الويك اند" }, { "en", "Weekend Flash Sale" } } },
                { "Terms_Flash_Body", new Dictionary<string, string> {
                { "ar", "يسري الخصم 25٪ كود [WEEK25] على قطع مختارة فقط لمدة 48 ساعة. الخصم لا يشمل التوصيل المجاني ولا يُجمع مع عروض أخرى. القسائم والكوبونات لا تشمل المنتجات المخفضة." },
                { "en", "The 25% discount code [WEEK25] applies to selected items only for 48 hours. The discount does not include free shipping and cannot be combined with other offers. Vouchers and coupons do not apply to discounted products." } } },
                { "Terms_Liability_Title", new Dictionary<string, string> { { "ar", "المسؤولية والخصوصية" }, { "en", "Liability & Privacy" } } },
                { "Terms_Liability_Body", new Dictionary<string, string> {
                { "ar", "تخضع عملية تقديمك لمعلومات شخصية لسياسة الخصوصية. استخدامك للموقع يتم على مسؤوليتك الخاصة. لا تضمن (صاد) خلو الموقع من الانقطاع أو الأخطاء، ولا تتحمل مسؤولية أي أضرار ناتجة عن استخدامه. أنت توافق على الدفاع عن (صاد) وتعويضها ضد أي مطالبات." },
                { "en", "Your submission of personal information is subject to our Privacy Policy. Your use of the site is at your own risk. Saad does not guarantee the site is free from interruptions or errors and is not liable for damages resulting from its use. You agree to indemnify and defend Saad against any claims." }} },
                { "Terms_Legal_Title", new Dictionary<string, string> { { "ar", "القانون والنزاعات" }, { "en", "Law & Disputes" } } },
                { "Terms_Legal_Body", new Dictionary<string, string> {
                { "ar", "تشكل هذه الأحكام الاتفاقية الكاملة. في حالة بطلان أي جزء، يظل الباقي سارياً. تخضع هذه الأحكام لقوانين المملكة العربية السعودية. يوافق الطرفان على محاولة حل النزاعات ودياً خلال 30 يوماً قبل اللجوء للقضاء." },
                { "en", "These terms constitute the entire agreement. If any part is void, the rest remains valid. These terms are governed by the laws of Saudi Arabia. Parties agree to attempt amicable dispute resolution within 30 days before legal action." }} },
                { "Terms_Orders_Title", new Dictionary<string, string> { { "ar", "الطلبات والأسعار" }, { "en", "Orders & Pricing" } } },
                { "Terms_Orders_Body", new Dictionary<string, string> {
                { "ar", "تخضع جميع الطلبات للقبول. نحتفظ بالحق في رفض أو إلغاء الطلب لأي سبب. قد لا يكون توفر البضائع مضموناً دائماً. جميع الأسعار صحيحة عند دخولك الموقع وقد تتغير." },
                { "en", "All orders are subject to acceptance. We reserve the right to refuse or cancel orders for any reason. Stock availability is not guaranteed. All prices are correct at the time of entry but may change." }} },
                { "Terms_Comments_Title", new Dictionary<string, string> { { "ar", "الردود والتعليقات" }, { "en", "Replies & Comments" } } },
                { "Terms_Comments_Body", new Dictionary<string, string> {
                { "ar", "نرحب بالتعليقات، لكن لا نقبل أي معلومات سرية. كل المشاركات ستصبح ملكية حصرية لـ (صاد). يمنع استخدام لغة بذيئة أو عناوين مزيفة. نحتفظ بالحق في حذف أو تعديل البيانات." },
                { "en", "We welcome comments but do not accept confidential info. All submissions become exclusive property of Saad. Profanity or fake addresses are prohibited. We reserve the right to delete or edit data." }} },
                { "Terms_Payment_Title", new Dictionary<string, string> { { "ar", "الأسعار وسياسة الدفع" }, { "en", "Prices & Payment Policy" } } },
                { "Terms_Payment_Body", new Dictionary<string, string> {
                { "ar", "الأسعار تشمل ضريبة القيمة المضافة. الدفع عبر البطاقات يخضع للتحقق. يجب تطابق بيانات البطاقة مع حاملها. لن تُخزن بيانات البطاقات أو تباع لأطراف ثالثة باستثناء بوابة الدفع." },
                { "en", "Prices include VAT. Card payments are subject to verification. Card details must match the holder. Card data will not be stored or sold to third parties, except for the payment gateway." }} },
                { "Terms_Offers_Title", new Dictionary<string, string> { { "ar", "العروض والتخفيضات" }, { "en", "Offers & Discounts" } } },
                { "Terms_Offers_Body", new Dictionary<string, string> {
                { "ar", "كود [free10] يمنح توصيلاً مجانياً لمدة 6 أشهر للطلبات فوق 199 ريال (تطبيق فقط). كود ACTAN يشمل (جديد صاد). كود AC100 يشمل (جديد صاد) باستثناء المخفض." },
                { "en", "Code [free10] gives free shipping for 6 months for orders over 199 SAR (App only). ACTAN code applies to (New Saad). AC100 code applies to (New Saad) excluding discounted items." }} },
                { "Terms_ReturnOffers_Title", new Dictionary<string, string> { { "ar", "سياسة إرجاع العروض" }, { "en", "Offer Return Policy" } } },
                { "Terms_ReturnOffers_Body", new Dictionary<string, string> {
                { "ar", "الطلبات ضمن عرض (قطعتين بسعر 95): لا يمكن إرجاع قطعة منفصلة، يشترط إرجاع العرض كاملاً. عند شراء أكثر من قطعتين، يقتصر الإرجاع على عدد زوجي." },
                { "en", "Orders within (2 for 95) offer: Individual items cannot be returned; the full offer must be returned. For more than 2 items, returns must be in even numbers." }} },
                { "Terms_EditOrder_Title", new Dictionary<string, string> { { "ar", "تعديل الطلبات" }, { "en", "Order Modification" } } },
                { "Terms_EditOrder_Body", new Dictionary<string, string> {
                { "ar", "حرصاً على سرعة التنفيذ، الطلب يصبح نهائياً وغير قابل للتعديل بعد الدفع. يتحمل العميل مسؤولية مراجعة البيانات قبل الإتمام." },
                { "en", "For speed of execution, the order becomes final and unmodifiable after payment. The customer is responsible for reviewing data before completion." }} },
                { "Title (Ar)", new Dictionary<string, string> { { "ar", "العنوان (عربي)" }, { "en", "Title (Ar)" } } },
                { "Title (En)", new Dictionary<string, string> { { "ar", "العنوان (إنجليزي)" }, { "en", "Title (En)" } } },
                { "Content (Ar)", new Dictionary<string, string> { { "ar", "المحتوى (عربي)" }, { "en", "Content (Ar)" } } },
                { "Content (En)", new Dictionary<string, string> { { "ar", "المحتوى (إنجليزي)" }, { "en", "Content (En)" } } },
                { "City / Region (Ar)", new Dictionary<string, string> { { "ar", "المدينة / المنطقة (عربي)" }, { "en", "City / Region (Ar)" } } },
                { "City / Region (En)", new Dictionary<string, string> { { "ar", "المدينة / المنطقة (إنجليزي)" }, { "en", "City / Region (En)" } } },
                { "Wallet Balance", new Dictionary<string, string> { { "ar", "رصيد المحفظة" }, { "en", "Wallet Balance" } } },
                { "Edit User", new Dictionary<string, string> { { "ar", "تعديل المستخدم" }, { "en", "Edit User" } } },
                { "User Details", new Dictionary<string, string> { { "ar", "تفاصيل المستخدم" }, { "en", "User Details" } } },
                { "Send Notification", new Dictionary<string, string> { { "ar", "إرسال إشعار" }, { "en", "Send Notification" } } },
                { "Notification Title", new Dictionary<string, string> { { "ar", "عنوان الإشعار" }, { "en", "Notification Title" } } },
                { "Notification Body", new Dictionary<string, string> { { "ar", "نص الإشعار" }, { "en", "Notification Body" } } },
                { "Notification Sent", new Dictionary<string, string> { { "ar", "تم إرسال الإشعار بنجاح" }, { "en", "Notification sent successfully" } } },
                { "Pending Payment Orders", new Dictionary<string, string> { { "ar", "طلبات بانتظار الدفع" }, { "en", "Orders Pending Payment" } } },
                { "Current Balance", new Dictionary<string, string> { { "ar", "الرصيد الحالي" }, { "en", "Current Balance" } } },
                { "Shipping Address", new Dictionary<string, string> { { "ar", "عنوان الشحن" }, { "en", "Shipping Address" } } },
                { "Order Items", new Dictionary<string, string> { { "ar", "المنتجات المطلوبة" }, { "en", "Order Items" } } },
                { "Payment Summary", new Dictionary<string, string> { { "ar", "ملخص الدفع" }, { "en", "Payment Summary" } } },
                { "Order Date", new Dictionary<string, string> { { "ar", "تاريخ الطلب" }, { "en", "Order Date" } } },
                { "Track Order", new Dictionary<string, string> { { "ar", "تتبع الطلب" }, { "en", "Track Order" } } },
                { "Order Placed", new Dictionary<string, string> { { "ar", "تم الطلب" }, { "en", "Order Placed" } } },
                { "Processing", new Dictionary<string, string> { { "ar", "تجهيز الطلب" }, { "en", "Processing" } } },
                { "Shipped", new Dictionary<string, string> { { "ar", "تم الشحن" }, { "en", "Shipped" } } },
                { "Delivered", new Dictionary<string, string> { { "ar", "تم التوصيل" }, { "en", "Delivered" } } },
                { "Back to Orders", new Dictionary<string, string> { { "ar", "العودة للطلبات" }, { "en", "Back to Orders" } } },
                { "Return Eligible until", new Dictionary<string, string> { { "ar", "متاح للإرجاع حتى" }, { "en", "Return eligible until" } } },
                { "Product", new Dictionary<string, string> { { "ar", "المنتج" }, { "en", "Product" } } },
            };
        }

        public string Get(string key)
        {
            if (string.IsNullOrEmpty(key)) return "";
            var culture = CultureInfo.CurrentCulture.Name;
            var langCode = culture.StartsWith("ar") ? "ar" : "en";

            if (_resources.ContainsKey(key) && _resources[key].ContainsKey(langCode))
            {
                return _resources[key][langCode];
            }

            return key;
        }

        public bool IsRtl()
        {
            return CultureInfo.CurrentCulture.Name.StartsWith("ar");
        }
    }
}